/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CollectionModelEntityModelProject } from '../../models/collection-model-entity-model-project';

export interface ExecuteSearchProjectGet1$Params {
}

export function executeSearchProjectGet1(http: HttpClient, rootUrl: string, params?: ExecuteSearchProjectGet1$Params, context?: HttpContext): Observable<StrictHttpResponse<CollectionModelEntityModelProject>> {
  const rb = new RequestBuilder(rootUrl, executeSearchProjectGet1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CollectionModelEntityModelProject>;
    })
  );
}

executeSearchProjectGet1.PATH = '/projects/search/countProjectsByStatus';
