/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
<<<<<<< HEAD
  rootUrl: string = 'http://localhost:8086/planning';
=======
  rootUrl: string = 'http://localhost:8085/planning';
>>>>>>> origin/lahmer
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
