/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { GanttChartControllerService } from './services/gantt-chart-controller.service';
export { TaskControllerService } from './services/task-controller.service';
