version:  "3.0"

services:
  project:
    build: ./Project
    image: abirbahraoui16/project:1.0
    container_name: project
    ports:
      - 8091:8091
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/projectMS?createDatabaseIfNotExist=true&useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
      - eureka
  eureka:
    build: ./Eureka
    image: abirbahraoui16/eureka:1.0
    container_name: eureka
    ports:
      - 8761:8761
  apiGateway:
    build: ./ApiGateway
    image: abirbahraoui16/apigateway:1.0
    container_name: apigateway
    ports:
      - 8090:8090
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
      - project
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobdb
    restart: unless-stopped
    volumes:
      - C:/xampp/mysql/data:/var/lib/mysql #Persistance entre la BD locale avec les containers
#      - mysql:/var/lib/mysql #Persistance des données entre containers
#volumes:
#  mysql
