/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Planning } from '../../models/planning';

export interface AddPlanning$Params {
      body: Planning
}

export function addPlanning(http: HttpClient, rootUrl: string, params: AddPlanning$Params, context?: HttpContext): Observable<StrictHttpResponse<Planning>> {
  const rb = new RequestBuilder(rootUrl, addPlanning.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Planning>;
    })
  );
}

addPlanning.PATH = '/Plan/add';
