/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Planning } from '../../models/planning';

export interface AssignTasksToPlanning$Params {
  idPlan: number;
  taskIds: Array<number>;
}

export function assignTasksToPlanning(http: HttpClient, rootUrl: string, params: AssignTasksToPlanning$Params, context?: HttpContext): Observable<StrictHttpResponse<Planning>> {
  const rb = new RequestBuilder(rootUrl, assignTasksToPlanning.PATH, 'put');
  if (params) {
    rb.path('idPlan', params.idPlan, {});
    rb.query('taskIds', params.taskIds, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Planning>;
    })
  );
}

assignTasksToPlanning.PATH = '/Plan/{idPlan}/assignTasks';
