/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Planning } from '../../models/planning';

export interface GetAllPlannings$Params {
}

export function getAllPlannings(http: HttpClient, rootUrl: string, params?: GetAllPlannings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Planning>>> {
  const rb = new RequestBuilder(rootUrl, getAllPlannings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Planning>>;
    })
  );
}

getAllPlannings.PATH = '/Plan/getPlannings';
