/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Planning } from '../../models/planning';

export interface GetPlanningById$Params {
  idPlan: number;
}

export function getPlanningById(http: HttpClient, rootUrl: string, params: GetPlanningById$Params, context?: HttpContext): Observable<StrictHttpResponse<Planning>> {
  const rb = new RequestBuilder(rootUrl, getPlanningById.PATH, 'get');
  if (params) {
    rb.path('idPlan', params.idPlan, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Planning>;
    })
  );
}

getPlanningById.PATH = '/Plan/getPlanningById/{idPlan}';
