/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Task } from '../models/task';
export interface GanttChart {
  endDate?: string;
  id: number;
  progress: number;
  startDate: string;
  taskName: string;
  tasks: Array<Task>;
}
