/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthenficationRequest } from '../../models/authenfication-request';
import { AuthenficationResponse } from '../../models/authenfication-response';

export interface Authenticate$Params {
      body: AuthenficationRequest
}

export function authenticate(http: HttpClient, rootUrl: string, params: Authenticate$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenficationResponse>> {
  const rb = new RequestBuilder(rootUrl, authenticate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
<<<<<<< HEAD
    rb.build({ responseType: 'json', accept: 'application/json', context })
=======
    rb.build({ responseType: 'json', accept: 'application/json ', context })
>>>>>>> origin/lahmer
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthenficationResponse>;
    })
  );
}

authenticate.PATH = '/auth/authenticate';
