/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityModelProject } from '../../models/entity-model-project';

export interface GetItemResourceProjectGet$Params {
  id: string;
}

export function getItemResourceProjectGet(http: HttpClient, rootUrl: string, params: GetItemResourceProjectGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EntityModelProject>> {
  const rb = new RequestBuilder(rootUrl, getItemResourceProjectGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntityModelProject>;
    })
  );
}

getItemResourceProjectGet.PATH = '/projects/{id}';
