/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityModelProject } from '../../models/entity-model-project';
import { ProjectRequestBody } from '../../models/project-request-body';

export interface PutItemResourceProjectPut$Params {
  id: string;
      body: ProjectRequestBody
}

export function putItemResourceProjectPut(http: HttpClient, rootUrl: string, params: PutItemResourceProjectPut$Params, context?: HttpContext): Observable<StrictHttpResponse<EntityModelProject>> {
  const rb = new RequestBuilder(rootUrl, putItemResourceProjectPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntityModelProject>;
    })
  );
}

putItemResourceProjectPut.PATH = '/projects/{id}';
