/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GanttChart } from '../../models/gantt-chart';

export interface GetGanttChartById$Params {
  id: number;
}

export function getGanttChartById(http: HttpClient, rootUrl: string, params: GetGanttChartById$Params, context?: HttpContext): Observable<StrictHttpResponse<GanttChart>> {
  const rb = new RequestBuilder(rootUrl, getGanttChartById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GanttChart>;
    })
  );
}

getGanttChartById.PATH = '/gantt-chart/getGanttChartById/{id}';
