/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GanttChart } from '../../models/gantt-chart';

export interface GetAllGanttCharts$Params {
}

export function getAllGanttCharts(http: HttpClient, rootUrl: string, params?: GetAllGanttCharts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GanttChart>>> {
  const rb = new RequestBuilder(rootUrl, getAllGanttCharts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GanttChart>>;
    })
  );
}

getAllGanttCharts.PATH = '/gantt-chart/all';
