/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Facture } from '../../models/facture';

export interface RetrieveById$Params {
  idF: number;
}

export function retrieveById(http: HttpClient, rootUrl: string, params: RetrieveById$Params, context?: HttpContext): Observable<StrictHttpResponse<Facture>> {
  const rb = new RequestBuilder(rootUrl, retrieveById.PATH, 'get');
  if (params) {
    rb.path('idF', params.idF, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Facture>;
    })
  );
}

retrieveById.PATH = '/Rest/findById/{idF}';
