/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Facture } from '../../models/facture';

export interface RetrieveAllFacture$Params {
}

export function retrieveAllFacture(http: HttpClient, rootUrl: string, params?: RetrieveAllFacture$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Facture>>> {
  const rb = new RequestBuilder(rootUrl, retrieveAllFacture.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Facture>>;
    })
  );
}

retrieveAllFacture.PATH = '/Rest/getAllFacture';
