/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModelProject } from '../models/entity-model-project';
import { Links } from '../models/links';
export interface CollectionModelEntityModelProject {
  '_embedded'?: {
'projects'?: Array<EntityModelProject>;
};
  '_links'?: Links;
}
