/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Links } from '../models/links';
export interface EntityModelProject {
  '_links'?: Links;
  city?: string;
  description?: string;
  endDate?: string;
  latitude?: string;
  location?: string;
  longitude?: string;
  name?: string;
  startDate?: string;
  status?: 'ON_GOING' | 'COMPLETED' | 'DELAYED';
}
