/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModelProject } from '../models/entity-model-project';
import { Links } from '../models/links';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelEntityModelProject {
  '_embedded'?: {
'projects'?: Array<EntityModelProject>;
};
  '_links'?: Links;
  page?: PageMetadata;
}
