/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectRequestBody {
  city?: string;
  description?: string;
  endDate?: string;
  idProject?: number;
  latitude?: string;
  location?: string;
  longitude?: string;
  name?: string;
  startDate?: string;
  status?: 'ON_GOING' | 'COMPLETED' | 'DELAYED';
}
