/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CredentialRepresentation {
  /** @deprecated */algorithm?: string;
  /** @deprecated */config?: {
'empty'?: boolean;
[key: string]: Array<string> | boolean | undefined;
};
  /** @deprecated */counter?: number;
  createdDate?: number;
  credentialData?: string;
  /** @deprecated */device?: string;
  /** @deprecated */digits?: number;
  /** @deprecated */hashIterations?: number;
  /** @deprecated */hashedSaltedValue?: string;
  id?: string;
  /** @deprecated */period?: number;
  priority?: number;
  /** @deprecated */salt?: string;
  secretData?: string;
  temporary?: boolean;
  type?: string;
  userLabel?: string;
  value?: string;
}
