/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  dateOfBirth: Date;
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
