/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SocialLinkRepresentation {
  socialProvider?: string;
  socialUserId?: string;
  socialUsername?: string;
}
