/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileAttributeGroupMetadata {
  annotations?: {
[key: string]: {
};
};
  displayDescription?: string;
  displayHeader?: string;
  name?: string;
}
