/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserConsentRepresentation {
  clientId?: string;
  createdDate?: number;
  grantedClientScopes?: Array<string>;
  /** @deprecated */grantedRealmRoles?: Array<string>;
  lastUpdatedDate?: number;
}
