/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileAttributeMetadata {
  annotations?: {
[key: string]: {
};
};
  displayName?: string;
  group?: string;
  multivalued?: boolean;
  name?: string;
  readOnly?: boolean;
  required?: boolean;
  validators?: {
[key: string]: {
[key: string]: {
};
};
};
}
