/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserProfileAttributeGroupMetadata } from '../models/user-profile-attribute-group-metadata';
import { UserProfileAttributeMetadata } from '../models/user-profile-attribute-metadata';
export interface UserProfileMetadata {
  attributes?: Array<UserProfileAttributeMetadata>;
  groups?: Array<UserProfileAttributeGroupMetadata>;
}
